name: contracts
description: Code generator to use smart contracts with a Dart API.
# version: 0.1.0
# homepage: https://www.example.com
# author: Simon Binder <email@example.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  dart_style: ^1.2.0
  web3dart: ">=1.0.0-rc.2 <2.0.0"
  build: ^1.1.4
  path: ^1.6.2

dev_dependencies:
  pedantic: ^1.0.0
  code_builder: ^3.2.0
  build_runner: ^1.3.0
  test: ^1.0.0
