import 'dart:async';

import 'package:build/build.dart';
import 'package:path/path.dart' as p;

class ContractsBuilder implements Builder {

  @override
  final Map<String, List<String>> buildExtensions = const {
    '.abi.json': ['.g.dart']
  };

  @override
  FutureOr<void> build(BuildStep buildStep) async {
    final input = buildStep.inputId;
    final target = AssetId(input.package, p.join(p.dirname(input.path), 'test.g.dart'));
    await buildStep.writeAsString(target, '// test file generated by contracts');
  }

}